#ifndef _PROJECT_H
#define _PROJECT_H

// file to test if generated header by cmock can find this header
// cmock shouldn't receive preprocessed file with expanded headers paths
// for autogenerated header without inline function definition

#define INLINE_HEADER_FUNCTION_RETURN_VAL 1

#endif